baseURL = "https://dsx-tech.github.io/Java-Reactive-Configuration/"
languageCode = "en-us"
title = "Java Reactive Config"
themesDir = "themes"
theme = "book"

# Code highlight
# pygmentsStyle = 'monokailight'
pygmentsCodeFences = true


[params]
    BookSection = 'docs'
